name: Flake8 Lint

on: [push, pull_request]

jobs:
  run-linter:
    name: Run Flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install flake8
      run: |
        python -m pip install flake8

    - name: Run flake8 Lint
      run: |
        flake8 .
